"""empty message

Revision ID: 3d2830c6c458
Revises: 
Create Date: 2020-04-29 04:21:26.467587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2830c6c458'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headers',
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=16), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('fancy_user_agent', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index(op.f('ix_headers_country'), 'headers', ['country'], unique=False)
    op.create_index(op.f('ix_headers_fancy_user_agent'), 'headers', ['fancy_user_agent'], unique=False)
    op.create_index(op.f('ix_headers_timestamp'), 'headers', ['timestamp'], unique=False)
    op.create_index(op.f('ix_headers_user_agent'), 'headers', ['user_agent'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_headers_user_agent'), table_name='headers')
    op.drop_index(op.f('ix_headers_timestamp'), table_name='headers')
    op.drop_index(op.f('ix_headers_fancy_user_agent'), table_name='headers')
    op.drop_index(op.f('ix_headers_country'), table_name='headers')
    op.drop_table('headers')
    # ### end Alembic commands ###
