"""empty message

Revision ID: 4d8de1c3d6e1
Revises: 616ad464b3d1
Create Date: 2020-04-29 03:53:24.221691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8de1c3d6e1'
down_revision = '616ad464b3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('headers', sa.Column('fancy_user_agent', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_headers_fancy_user_agent'), 'headers', ['fancy_user_agent'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_headers_fancy_user_agent'), table_name='headers')
    op.drop_column('headers', 'fancy_user_agent')
    # ### end Alembic commands ###
