"""empty message

Revision ID: 616ad464b3d1
Revises: 10756ac1657d
Create Date: 2020-04-29 03:29:06.133218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616ad464b3d1'
down_revision = '10756ac1657d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_headers_country', table_name='headers')
    op.create_index(op.f('ix_headers_country'), 'headers', ['country'], unique=False)
    op.drop_index('ix_headers_user_agent', table_name='headers')
    op.create_index(op.f('ix_headers_user_agent'), 'headers', ['user_agent'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_headers_user_agent'), table_name='headers')
    op.create_index('ix_headers_user_agent', 'headers', ['user_agent'], unique=1)
    op.drop_index(op.f('ix_headers_country'), table_name='headers')
    op.create_index('ix_headers_country', 'headers', ['country'], unique=1)
    # ### end Alembic commands ###
